[font]
size = 12.0

[font.normal]
family = "Comic Code Medium"
style = "Regular"

[font.bold]
family = "Comic Code Bold"
style = "Bold"

[font.italic]
family = "Comic Code Italic"
style = "Italic"

[font.bold_italic]
family = "Comic Code Bold Italic"
style = "Bold Italic"
